### ISSUE TITLE
YAML example uses anchor syntax

### ISSUE THREAD

**Issue by mariduv** [bluefeet/Config-MethodProxy#1]
``` yaml

---
db:
    dsn: DBI:mysql:database=foo
    username: bar
    password:
        - &proxy
        - MyApp::Config
        - get_db_password
        - bar
```

``` perl
{
  db => {
    password => [undef, 'MyApp::Config', 'get_db_password', 'bar'],
    dsn => 'DBI:mysql:database=foo',
    username => 'bar'
  }
}
```

The YAML example provided will parse `&proxy` as an anchor since it isn't quoted, making the value `undef` (a list item of nothing with a named anchor to it) rather than getting that `"&proxy"` back for the library to handle.
